### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ryndrb** [ryndrb/delta-em#2]
- [x] Replace Brendan and May sprites top FRLG style.
- [x] Replace all other NPC sprites to FRLG style.
- [x] Update Gen Info
  - [x] Gen 1
  - [x] Gen 2
  - [x] Gen 3
  - [x] Gen 4
  - [x] Gen 5
  - [x] Gen 6
  - [x] Gen 7
  - [x] Gen 8
  - [x] Gen 9
- [x] Add the new/old abilities from my CFRU and some from Inclement Emerald.
  - [x] Pyromancy
  - [x] Fatal Precision
  - [x] Adrenaline
  - [x] Grounded
  - [x] Poison Absorb
  - [x] Striker
  - [x] Psych
  - [x] Self Sufficient
  - [x] Chloroplast
  - [x] Power Fist
  - [x] Blitz Boxer
- [x] Add DexNav by Ghoulslash.
- [x] Decapitalization
  - [x] Hoenn map names.
- [x] Edit Summary screen to print EV, IV, and BS.
- [x] Edit summary screen to support three-line ability description.
- [ ] DNS
    - [ ] Day/Night wild encounters.
    - [ ] Create Time Changer.
- [ ] Replace Punk Rock ability of Explound line to Amplifier name.
- [ ] Populate Items in the overworld.
- [x] Overworld Signpost Missing
  - [ ] Make Seaspray Cave signpost
  - [x] Make Dewford Manor signpost
- [ ] Make Sandstream have immunity in sand.
- [x] Illuminate to resist Dark and gives 20% accuracy boost.
- [ ] Include Potion kid in Route 104.
- [x] Give Nat Dex at the start
- [x] MUSIC CHANGES AND ADDITIONS
     - [x] Pull cyan's music expansion (HGGS/DPPt only).
     - [x] Add Zinia ORAS theme/encounter/music.
     - [x] Add Wally ORAS theme.
     - [ ] Replace Archie event scene music with a more serious one (ORAS).
- [x] Sprite Changes
  - [ ] Change Captain Stern sprite
  - [x] Matching OW sprites for Trainer Front Pics
    - [ ] 
    - [ ] 
    - [ ] 
    - [ ] 
- [ ] TM Expansion
  - [x] NPC's TM Gifts Changes and Additions
    - [ ] Add Devon worker in Rustboro mart to give False Swipe TM
    - [x] Change Wattson TM gift to Volt Switch
    - [x] Cozmo gives TM Smack Down
    - [x] Lavaridge Black Belt gives TM Swords Dance
    - [ ] Change Facade TM to Retaliate by Norman
- [x] Clear Wattson Mauville flag capturing Kyogre and Groudon.
- [ ] Game Corner Item List
- [ ] Fix Secret Power guy in Route 111 (since TM Secret Power isn't anymore)

**Comment by ryndrb** [comment]
> ### Scripting

- [x] Littleroot Town
- [x] Route 101
- [x] Oldale Town
- [x] Route 103
- [x] Route 102
- [x] Petalburg City
    - [x] Petalburg Gym
- [x] Route 104
- [x] Petalburg Woods
- [x] Rustboro City
    - [x] Rustboro Gym
    - [x] Devon Corporation
        - [x] 1st
        - [x] 2nd
- [x] Rouet 116
- [x] Rusturf Tunnel
- [x] Route 105
- [x] Route 106
- [x] Dewford Town
    - [x] Dewford Gym
    - [ ] Dewford Meadow
        - [ ] Abandoned Manor
- [x] Granite Cave
    - [x] Steven's Room
- [x] Route 107
- [x] Route 108
- [x] Route 109
- [x] Slateport City
    - [x] Oceanic Museum
    - [ ] Contest Spectacular Hall
    - [x] Slateport Harbor
- [x] Route 110
    - [x] Trick House
    - [x] New Mauville
- [x] Mauvill City
    - [x] Mauvill Gym
- [x] Route 117
- [x] Verdanturf Town
- [x] Route 111 (South)
- [x] Route 112 (South)
- [x] Fiery Path
- [x] Route 112 (North)
- [x] Route 111 (North)
- [x] Route 113
- [x] Fallarbor Town
- [x] Route 114
- [x] Meteor Falls
- [x] Route 115
- [x] Mt. Chimney
- [x] Jagged Pass
    - [x] Team Magma Hideout
- [x] Lavaridge Town
    - [x] Lavaridge Gym
- [x] Route 111 (Desert)
- [x] Route 118
- [x] Southern Island
- [x] Route 119
    - [x] Weather Institute
- [x] Fortree City
    - [x] Fortree Gym
- [x] Route 120
- [x] Route 121
    - [x] Safari Zone
- [x] Route 122
- [x] Mt. Pyre
- [x] Route 123
- [x] Lilycove City
- [x] Team Aqua Hideout
- [x] Route 124
- [x] Mossdeep City
    - [x] Mossdeep Gym
    - [x] Space Center
- [x] Route 125
- [x] Shoal Cave
- [x] Route 127
- [x] Route 128
- [x] Seafloor Cavern
- [x] Route 126
- [x] Sootopolis City
    - [x] Sootopolis Gym
    - [x] Cave of Origin
- [x] Route 129
- [x] Route 130
- [x] Route 131
    - [x] Sky Pillar
        - [x] Rayquaza
        - [ ] Zinia
- [x] Pacifidlog Town
- [x] Route 132
- [x] Route 133
- [x] Route 134
- [ ] Sealed Chamber
- [ ] Island Cave
- [ ] Desert Ruins
- [ ] Ancient Tomb
- [ ] Scorched Slab
- [x] Evergrande City
- [x] Victory Road
- [ ] Pokemon League
